{{- range $name, $value := .Values.nodePools }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $.Values.clusterName }}-{{ $name }}
spec:
  amiFamily: Custom
  amiSelectorTerms:
    - id: {{ $value.amiId }}
    
  subnetSelectorTerms:
    - tags:
        sigs.k8s.io/cluster-api-provider-aws/cluster/{{ $.Values.clusterName }}: "owned"
        sigs.k8s.io/cluster-api-provider-aws/role: private

  securityGroupSelectorTerms:
    - tags:
        sigs.k8s.io/cluster-api-provider-aws/role: node
        sigs.k8s.io/cluster-api-provider-aws/cluster/{{ $.Values.clusterName }}: "owned"

  instanceProfile: "nodes-{{ $.Values.clusterName }}-{{ $name }}"

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1 # This is changed to disable IMDS access from containers not on the host network
    httpTokens: required

  # Optional, configures storage devices for the instance
  blockDeviceMappings:
    - deviceName: /dev/xvda
      rootVolume: true
      ebs:
        volumeSize: {{ $value.rootVolumeSizeGB }}
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvdd
      ebs:
        encrypted: true
        volumeSize: {{ $value.libVolumeSizeGB }}
        volumeType: gp3
        deleteOnTermination: true
    - deviceName: /dev/xvde
      ebs:
        encrypted: true
        volumeSize: {{ $value.logVolumeSizeGB }}
        volumeType: gp3
        deleteOnTermination: true

  # Optional, overrides autogenerated userdata with a merge semantic
  userData: |
    {"ignition":{"config":{"merge":[{"source":"s3://{{ $.Values.clusterRegion }}-capa-{{ $.Values.clusterName }}/karpenter-machine-pool/{{ $.Values.clusterName }}-{{ $name }}","verification":{}}],"replace":{"verification":{}}},"proxy":{},"security":{"tls":{}},"timeouts":{},"version":"3.4.0"},"kernelArguments":{},"passwd":{},"storage":{},"systemd":{}}
{{- end }}
