apiVersion: v2
appVersion: 1.0.0

name: karpenter-nodepools

description: Karpernter nodepools Helm chart for Giant Swarm Platform

home: https://github.com/giantswarm/karpenter-nodepools
icon: https://s.giantswarm.io/app-icons/karpenter/1/light.svg

version: 0.0.0-dev

annotations:
  application.giantswarm.io/team: phoenix
