clusterName: test
clusterRegion: eu-west-2
amiOwner: "706635527432"
baseOS: "3975.2.1"
k8sVersion: "1.20.0"
toolingVersion: "1.20.0"

nodePools:
  def00:
    limits:
      cpu: "1000"
      memory: "1000Gi"

    rootVolumeSizeGB: 8
    libVolumeSizeGB: 120
    logVolumeSizeGB: 30

    requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: NotIn
        values:
          - t3
          - t3a
          - t2
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
          - "4"
          - "8"
          - "16"
          - "32"
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
          - nitro
      - key: kubernetes.io/arch
        operator: In
        values:
          - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
          - spot
          - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
          - linux
